name: env_rcm_sar_calibration
channels:
  - terradue
  - conda-forge
dependencies:
  - python
  - click2cwl
  - pyyaml
  - snapista
  - gdal=3.1.4
  - shapely
  - snuggs
  - matplotlib
  - pip
  - rioxarray
  - pip:
      - pystac==1.0.0-beta.3
      - rio_color
  - snuggs